#####################################################
# General Config
#####################################################

tag: ${prompt}
seed: 0
height: 512
width: 512
save_baseline_comparison: false
baseline_num_inference_steps: 4

prompt: ""
negative_prompt: null

time_schedule: linear

#####################################################
# Stochastic Few Step Model Config
#####################################################
model: "flux"
mini_batch_size: 1
grad_minibatch_size: 1
true_cfg_scale: 1.0
guidance_scale: 3.5 # Not used for FLUX.1-Schnell

original_scheduler: linear
new_scheduler: vp
sample_method: sde
diffuse_coeff_func: rev_original
diffusion_norm: 1.0

save_vram: true

#####################################################
# MCMC Config
#####################################################

mcmc: pcnl
alpha_mcmc: 0.03

step_size: 0.5
num_mcmc_steps: 25
num_chains: 10
burn_in: 25
custom_call_function_name: thinning
grad_norm: 0.0001
grad_const_scale: 1.5

# pCNL Config
rho: null

#####################################################
# MCMC Scheduler Config
#####################################################

mcmc_scheduler: uniform

#####################################################
# SMC Config
#####################################################
runner: smc
alpha: 0.03 # SMC
num_particles: 20
num_inference_steps: 25
ess_threshold: 0.5
smc_grad_norm: 0.00025
smc_grad_const_scale: 1.0

return_max_reward: true
init_weight_method: reward
grad_scale: 1.0

#####################################################
# Reward Model Config
#####################################################

decode_to_unnormalized: false
